apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dockeriser
  name: dockeriser
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dockeriser
  template:
    metadata:
      labels:
        app: dockeriser
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      containers:
        - image: us.gcr.io/my-awesome-project/dockeriser:20201122_2020
          name: dockeriser
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: ENVIRONMENT_NAME
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: environment.name
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            periodSeconds: 2
            timeoutSeconds: 1
            initialDelaySeconds: 7
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            periodSeconds: 60
            timeoutSeconds: 5
            initialDelaySeconds: 30