apiVersion: v1
kind: Service
metadata:
  name: dockeriser-headless-service
spec:
  clusterIP: None
  selector:
    app: dockeriser
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
